'use client';

import { useState } from 'react';
import { X, Trash2, Pencil, Plus } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import type { MatterRule } from './bhavAutoFill';

// The astrologer's own Matter -> Rule library (e.g. "Higher Education" ->
// "Higher education is seen by the 9th Sub Lord..."). Editable here, no code
// changes needed to add a new matter's rule. Rule text is never generated by
// this app — only what the astrologer types in.
export default function MatterRuleLibrary({
  open,
  onClose,
  rules,
  onChanged,
}: {
  open: boolean;
  onClose: () => void;
  rules: MatterRule[];
  onChanged: () => void;
}) {
  const token = useAuth();
  const [keyword, setKeyword] = useState('');
  const [ruleText, setRuleText] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  if (!open) return null;

  const resetForm = () => {
    setKeyword('');
    setRuleText('');
    setEditingId(null);
  };

  const startEdit = (rule: MatterRule) => {
    setEditingId(rule._id || null);
    setKeyword(rule.keyword);
    setRuleText(rule.ruleText);
  };

  const save = async () => {
    if (!token || !keyword.trim() || !ruleText.trim()) return;
    setSaving(true);
    setError('');
    try {
      const url = editingId
        ? `/api/admin/crm/kp-astro/matter-rules/${editingId}`
        : '/api/admin/crm/kp-astro/matter-rules';
      const res = await fetch(url, {
        method: editingId ? 'PATCH' : 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ keyword: keyword.trim(), ruleText: ruleText.trim() }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to save rule');
      resetForm();
      onChanged();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to save rule');
    } finally {
      setSaving(false);
    }
  };

  const remove = async (rule: MatterRule) => {
    if (!token || !rule._id) return;
    if (!confirm(`Delete the rule for "${rule.keyword}"?`)) return;
    try {
      const res = await fetch(`/api/admin/crm/kp-astro/matter-rules/${rule._id}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${token}` },
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to delete rule');
      if (editingId === rule._id) resetForm();
      onChanged();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to delete rule');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-xl">
        <div className="flex items-center justify-between border-b border-gray-200 px-5 py-4">
          <div>
            <h3 className="text-sm font-semibold text-gray-900">Matter Rule Library</h3>
            <p className="mt-0.5 text-xs text-gray-500">Your own KP toolkit rules, matched by Matter keyword — auto-fills Rule when it matches.</p>
          </div>
          <button type="button" onClick={onClose} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="overflow-y-auto p-5">
          <div className="mb-4 space-y-2 rounded-xl border border-gray-200 bg-gray-50 p-3">
            <input
              type="text"
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              placeholder="Matter keyword — e.g. Higher Education"
              className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
            />
            <textarea
              value={ruleText}
              onChange={(e) => setRuleText(e.target.value)}
              placeholder="Rule text — e.g. Higher education is seen by the 9th Sub Lord..."
              rows={3}
              className="w-full resize-y rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
            />
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={save}
                disabled={saving || !keyword.trim() || !ruleText.trim()}
                className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50"
              >
                {editingId ? <Pencil className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}
                {editingId ? 'Save changes' : 'Add rule'}
              </button>
              {editingId && (
                <button type="button" onClick={resetForm} className="text-sm text-gray-500 hover:underline">
                  Cancel edit
                </button>
              )}
            </div>
            {error && <p className="text-xs text-red-600">{error}</p>}
          </div>

          <div className="space-y-2">
            {rules.length === 0 && <p className="text-sm text-gray-400">No rules yet — add your first one above.</p>}
            {rules.map((rule) => (
              <div key={rule._id} className="flex items-start justify-between gap-3 rounded-xl border border-gray-200 p-3">
                <div className="min-w-0">
                  <div className="text-sm font-semibold text-gray-900">{rule.keyword}</div>
                  <div className="mt-0.5 text-xs text-gray-600">{rule.ruleText}</div>
                </div>
                <div className="flex shrink-0 items-center gap-1">
                  <button type="button" onClick={() => startEdit(rule)} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-indigo-600">
                    <Pencil className="h-4 w-4" />
                  </button>
                  <button type="button" onClick={() => remove(rule)} className="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-red-600">
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
