import crypto from 'node:crypto';
import { bunnyBatch, bunnyExecute } from '@/lib/bunnyDatabase';

function parse<T>(value: unknown, fallback: T): T { try { return value ? JSON.parse(String(value)) as T : fallback; } catch { return fallback; } }
function map(row: any) { return { _id: String(row.id), zoomMeetingId: Number(row.zoom_meeting_id), zoomMeetingUuid: row.zoom_meeting_uuid, topic: row.topic, hostId: row.host_id, startTime: row.start_time, duration: Number(row.duration || 0), totalSize: Number(row.total_size || 0), syncedFiles: parse(row.synced_files_json, []), skippedFiles: parse(row.skipped_files_json, []), errors: parse(row.errors_json, []), syncStatus: row.sync_status, syncedAt: row.synced_at, workshopId: row.workshop_id || undefined }; }

export async function initBunnyZoomRecordingSchema() { await bunnyBatch([{ sql: `CREATE TABLE IF NOT EXISTS zoom_recording_sync_sql (id TEXT PRIMARY KEY,zoom_meeting_id TEXT NOT NULL,zoom_meeting_uuid TEXT NOT NULL UNIQUE,topic TEXT NOT NULL,host_id TEXT,start_time TEXT,duration INTEGER,total_size INTEGER,synced_files_json TEXT NOT NULL DEFAULT '[]',skipped_files_json TEXT NOT NULL DEFAULT '[]',errors_json TEXT NOT NULL DEFAULT '[]',sync_status TEXT NOT NULL DEFAULT 'pending',synced_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,workshop_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`, args: [] }, { sql: 'CREATE INDEX IF NOT EXISTS idx_zoom_recording_sync_sql_synced_at ON zoom_recording_sync_sql(synced_at)', args: [] }, { sql: 'CREATE INDEX IF NOT EXISTS idx_zoom_recording_sync_sql_topic ON zoom_recording_sync_sql(topic)', args: [] }]); }
export async function listBunnyZoomRecordings(search = '', page = 1, limit = 20) { await initBunnyZoomRecordingSchema(); const args: any[] = []; const where = search ? 'WHERE lower(topic) LIKE ?' : ''; if (search) args.push(`%${search.toLowerCase()}%`); const count = await bunnyExecute({ sql: `SELECT COUNT(*) AS count FROM zoom_recording_sync_sql ${where}`, args }); const rows = await bunnyExecute({ sql: `SELECT * FROM zoom_recording_sync_sql ${where} ORDER BY synced_at DESC LIMIT ? OFFSET ?`, args: [...args, limit, (page - 1) * limit] }); return { recordings: rows.rows.map(map), total: Number(count.rows[0]?.count || 0) }; }
export async function getBunnyZoomRecordingByUuid(uuid: string) { await initBunnyZoomRecordingSchema(); const result = await bunnyExecute({ sql: 'SELECT * FROM zoom_recording_sync_sql WHERE zoom_meeting_uuid = ?', args: [uuid] }); return result.rows[0] ? map(result.rows[0]) : null; }
export async function saveBunnyZoomRecording(input: any) { await initBunnyZoomRecordingSchema(); const id = input.id || crypto.randomUUID(); const timestamp = new Date().toISOString(); await bunnyExecute({ sql: `INSERT INTO zoom_recording_sync_sql (id,zoom_meeting_id,zoom_meeting_uuid,topic,host_id,start_time,duration,total_size,synced_files_json,skipped_files_json,errors_json,sync_status,synced_at,workshop_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(zoom_meeting_uuid) DO UPDATE SET synced_files_json=excluded.synced_files_json,skipped_files_json=excluded.skipped_files_json,errors_json=excluded.errors_json,sync_status=excluded.sync_status,synced_at=excluded.synced_at,updated_at=excluded.updated_at`, args: [id,String(input.zoomMeetingId),String(input.zoomMeetingUuid),String(input.topic || ''),input.hostId || null,input.startTime || null,Number(input.duration || 0),Number(input.totalSize || 0),JSON.stringify(input.syncedFiles || []),JSON.stringify(input.skippedFiles || []),JSON.stringify(input.errors || []),input.syncStatus || 'pending',input.syncedAt || timestamp,input.workshopId || null,timestamp,timestamp] }); return getBunnyZoomRecordingByUuid(String(input.zoomMeetingUuid)); }
