// lib/countryPhoneCodes.ts
// Comprehensive country phone codes with flags (200 countries)
// Shared across signup, community join, and forms pages.

export interface CountryPhoneInfo {
  code: string;
  flag: string;
}

export const COUNTRY_PHONE_CODES: Record<string, CountryPhoneInfo> = {
  'Afghanistan': { code: '+93', flag: '🇦🇫' },
  'Albania': { code: '+355', flag: '🇦🇱' },
  'Algeria': { code: '+213', flag: '🇩🇿' },
  'Andorra': { code: '+376', flag: '🇦🇩' },
  'Angola': { code: '+244', flag: '🇦🇴' },
  'Antigua and Barbuda': { code: '+1268', flag: '🇦🇬' },
  'Argentina': { code: '+54', flag: '🇦🇷' },
  'Armenia': { code: '+374', flag: '🇦🇲' },
  'Australia': { code: '+61', flag: '🇦🇺' },
  'Austria': { code: '+43', flag: '🇦🇹' },
  'Azerbaijan': { code: '+994', flag: '🇦🇿' },
  'Bahamas': { code: '+1242', flag: '🇧🇸' },
  'Bahrain': { code: '+973', flag: '🇧🇭' },
  'Bangladesh': { code: '+880', flag: '🇧🇩' },
  'Barbados': { code: '+1246', flag: '🇧🇧' },
  'Belarus': { code: '+375', flag: '🇧🇾' },
  'Belgium': { code: '+32', flag: '🇧🇪' },
  'Belize': { code: '+501', flag: '🇧🇿' },
  'Benin': { code: '+229', flag: '🇧🇯' },
  'Bhutan': { code: '+975', flag: '🇧🇹' },
  'Bolivia': { code: '+591', flag: '🇧🇴' },
  'Bosnia and Herzegovina': { code: '+387', flag: '🇧🇦' },
  'Botswana': { code: '+267', flag: '🇧🇼' },
  'Brazil': { code: '+55', flag: '🇧🇷' },
  'Brunei': { code: '+673', flag: '🇧🇳' },
  'Bulgaria': { code: '+359', flag: '🇧🇬' },
  'Burkina Faso': { code: '+226', flag: '🇧🇫' },
  'Burundi': { code: '+257', flag: '🇧🇮' },
  'Cambodia': { code: '+855', flag: '🇰🇭' },
  'Cameroon': { code: '+237', flag: '🇨🇲' },
  'Canada': { code: '+1', flag: '🇨🇦' },
  'Cape Verde': { code: '+238', flag: '🇨🇻' },
  'Central African Republic': { code: '+236', flag: '🇨🇫' },
  'Chad': { code: '+235', flag: '🇹🇩' },
  'Chile': { code: '+56', flag: '🇨🇱' },
  'China': { code: '+86', flag: '🇨🇳' },
  'Colombia': { code: '+57', flag: '🇨🇴' },
  'Comoros': { code: '+269', flag: '🇰🇲' },
  'Congo': { code: '+242', flag: '🇨🇬' },
  'Costa Rica': { code: '+506', flag: '🇨🇷' },
  'Croatia': { code: '+385', flag: '🇭🇷' },
  'Cuba': { code: '+53', flag: '🇨🇺' },
  'Cyprus': { code: '+357', flag: '🇨🇾' },
  'Czech Republic': { code: '+420', flag: '🇨🇿' },
  'Denmark': { code: '+45', flag: '🇩🇰' },
  'Djibouti': { code: '+253', flag: '🇩🇯' },
  'Dominica': { code: '+1767', flag: '🇩🇲' },
  'Dominican Republic': { code: '+1809', flag: '🇩🇴' },
  'Ecuador': { code: '+593', flag: '🇪🇨' },
  'Egypt': { code: '+20', flag: '🇪🇬' },
  'El Salvador': { code: '+503', flag: '🇸🇻' },
  'Equatorial Guinea': { code: '+240', flag: '🇬🇶' },
  'Eritrea': { code: '+291', flag: '🇪🇷' },
  'Estonia': { code: '+372', flag: '🇪🇪' },
  'Eswatini': { code: '+268', flag: '🇸🇿' },
  'Ethiopia': { code: '+251', flag: '🇪🇹' },
  'Fiji': { code: '+679', flag: '🇫🇯' },
  'Finland': { code: '+358', flag: '🇫🇮' },
  'France': { code: '+33', flag: '🇫🇷' },
  'Gabon': { code: '+241', flag: '🇬🇦' },
  'Gambia': { code: '+220', flag: '🇬🇲' },
  'Georgia': { code: '+995', flag: '🇬🇪' },
  'Germany': { code: '+49', flag: '🇩🇪' },
  'Ghana': { code: '+233', flag: '🇬🇭' },
  'Greece': { code: '+30', flag: '🇬🇷' },
  'Grenada': { code: '+1473', flag: '🇬🇩' },
  'Guatemala': { code: '+502', flag: '🇬🇹' },
  'Guinea': { code: '+224', flag: '🇬🇳' },
  'Guinea-Bissau': { code: '+245', flag: '🇬🇼' },
  'Guyana': { code: '+592', flag: '🇬🇾' },
  'Haiti': { code: '+509', flag: '🇭🇹' },
  'Honduras': { code: '+504', flag: '🇭🇳' },
  'Hungary': { code: '+36', flag: '🇭🇺' },
  'Iceland': { code: '+354', flag: '🇮🇸' },
  'India': { code: '+91', flag: '🇮🇳' },
  'Indonesia': { code: '+62', flag: '🇮🇩' },
  'Iran': { code: '+98', flag: '🇮🇷' },
  'Iraq': { code: '+964', flag: '🇮🇶' },
  'Ireland': { code: '+353', flag: '🇮🇪' },
  'Israel': { code: '+972', flag: '🇮🇱' },
  'Italy': { code: '+39', flag: '🇮🇹' },
  'Ivory Coast': { code: '+225', flag: '🇨🇮' },
  'Jamaica': { code: '+1876', flag: '🇯🇲' },
  'Japan': { code: '+81', flag: '🇯🇵' },
  'Jordan': { code: '+962', flag: '🇯🇴' },
  'Kazakhstan': { code: '+7', flag: '🇰🇿' },
  'Kenya': { code: '+254', flag: '🇰🇪' },
  'Kiribati': { code: '+686', flag: '🇰🇮' },
  'Kosovo': { code: '+383', flag: '🇽🇰' },
  'Kuwait': { code: '+965', flag: '🇰🇼' },
  'Kyrgyzstan': { code: '+996', flag: '🇰🇬' },
  'Laos': { code: '+856', flag: '🇱🇦' },
  'Latvia': { code: '+371', flag: '🇱🇻' },
  'Lebanon': { code: '+961', flag: '🇱🇧' },
  'Lesotho': { code: '+266', flag: '🇱🇸' },
  'Liberia': { code: '+231', flag: '🇱🇷' },
  'Libya': { code: '+218', flag: '🇱🇾' },
  'Liechtenstein': { code: '+423', flag: '🇱🇮' },
  'Lithuania': { code: '+370', flag: '🇱🇹' },
  'Luxembourg': { code: '+352', flag: '🇱🇺' },
  'Madagascar': { code: '+261', flag: '🇲🇬' },
  'Malawi': { code: '+265', flag: '🇲🇼' },
  'Malaysia': { code: '+60', flag: '🇲🇾' },
  'Maldives': { code: '+960', flag: '🇲🇻' },
  'Mali': { code: '+223', flag: '🇲🇱' },
  'Malta': { code: '+356', flag: '🇲🇹' },
  'Marshall Islands': { code: '+692', flag: '🇲🇭' },
  'Mauritania': { code: '+222', flag: '🇲🇷' },
  'Mauritius': { code: '+230', flag: '🇲🇺' },
  'Mexico': { code: '+52', flag: '🇲🇽' },
  'Micronesia': { code: '+691', flag: '🇫🇲' },
  'Moldova': { code: '+373', flag: '🇲🇩' },
  'Monaco': { code: '+377', flag: '🇲🇨' },
  'Mongolia': { code: '+976', flag: '🇲🇳' },
  'Montenegro': { code: '+382', flag: '🇲🇪' },
  'Morocco': { code: '+212', flag: '🇲🇦' },
  'Mozambique': { code: '+258', flag: '🇲🇿' },
  'Myanmar': { code: '+95', flag: '🇲🇲' },
  'Namibia': { code: '+264', flag: '🇳🇦' },
  'Nauru': { code: '+674', flag: '🇳🇷' },
  'Nepal': { code: '+977', flag: '🇳🇵' },
  'Netherlands': { code: '+31', flag: '🇳🇱' },
  'New Zealand': { code: '+64', flag: '🇳🇿' },
  'Nicaragua': { code: '+505', flag: '🇳🇮' },
  'Niger': { code: '+227', flag: '🇳🇪' },
  'Nigeria': { code: '+234', flag: '🇳🇬' },
  'North Korea': { code: '+850', flag: '🇰🇵' },
  'North Macedonia': { code: '+389', flag: '🇲🇰' },
  'Norway': { code: '+47', flag: '🇳🇴' },
  'Oman': { code: '+968', flag: '🇴🇲' },
  'Pakistan': { code: '+92', flag: '🇵🇰' },
  'Palau': { code: '+680', flag: '🇵🇼' },
  'Palestine': { code: '+970', flag: '🇵🇸' },
  'Panama': { code: '+507', flag: '🇵🇦' },
  'Papua New Guinea': { code: '+675', flag: '🇵🇬' },
  'Paraguay': { code: '+595', flag: '🇵🇾' },
  'Peru': { code: '+51', flag: '🇵🇪' },
  'Philippines': { code: '+63', flag: '🇵🇭' },
  'Poland': { code: '+48', flag: '🇵🇱' },
  'Portugal': { code: '+351', flag: '🇵🇹' },
  'Qatar': { code: '+974', flag: '🇶🇦' },
  'Romania': { code: '+40', flag: '🇷🇴' },
  'Russia': { code: '+7', flag: '🇷🇺' },
  'Rwanda': { code: '+250', flag: '🇷🇼' },
  'Saint Kitts and Nevis': { code: '+1869', flag: '🇰🇳' },
  'Saint Lucia': { code: '+1758', flag: '🇱🇨' },
  'Saint Vincent and the Grenadines': { code: '+1784', flag: '🇻🇨' },
  'Samoa': { code: '+685', flag: '🇼🇸' },
  'San Marino': { code: '+378', flag: '🇸🇲' },
  'Sao Tome and Principe': { code: '+239', flag: '🇸🇹' },
  'Saudi Arabia': { code: '+966', flag: '🇸🇦' },
  'Senegal': { code: '+221', flag: '🇸🇳' },
  'Serbia': { code: '+381', flag: '🇷🇸' },
  'Seychelles': { code: '+248', flag: '🇸🇨' },
  'Sierra Leone': { code: '+232', flag: '🇸🇱' },
  'Singapore': { code: '+65', flag: '🇸🇬' },
  'Slovakia': { code: '+421', flag: '🇸🇰' },
  'Slovenia': { code: '+386', flag: '🇸🇮' },
  'Solomon Islands': { code: '+677', flag: '🇸🇧' },
  'Somalia': { code: '+252', flag: '🇸🇴' },
  'South Africa': { code: '+27', flag: '🇿🇦' },
  'South Korea': { code: '+82', flag: '🇰🇷' },
  'South Sudan': { code: '+211', flag: '🇸🇸' },
  'Spain': { code: '+34', flag: '🇪🇸' },
  'Sri Lanka': { code: '+94', flag: '🇱🇰' },
  'Sudan': { code: '+249', flag: '🇸🇩' },
  'Suriname': { code: '+597', flag: '🇸🇷' },
  'Sweden': { code: '+46', flag: '🇸🇪' },
  'Switzerland': { code: '+41', flag: '🇨🇭' },
  'Syria': { code: '+963', flag: '🇸🇾' },
  'Taiwan': { code: '+886', flag: '🇹🇼' },
  'Tajikistan': { code: '+992', flag: '🇹🇯' },
  'Tanzania': { code: '+255', flag: '🇹🇿' },
  'Thailand': { code: '+66', flag: '🇹🇭' },
  'Timor-Leste': { code: '+670', flag: '🇹🇱' },
  'Togo': { code: '+228', flag: '🇹🇬' },
  'Tonga': { code: '+676', flag: '🇹🇴' },
  'Trinidad and Tobago': { code: '+1868', flag: '🇹🇹' },
  'Tunisia': { code: '+216', flag: '🇹🇳' },
  'Turkey': { code: '+90', flag: '🇹🇷' },
  'Turkmenistan': { code: '+993', flag: '🇹🇲' },
  'Tuvalu': { code: '+688', flag: '🇹🇻' },
  'Uganda': { code: '+256', flag: '🇺🇬' },
  'Ukraine': { code: '+380', flag: '🇺🇦' },
  'United Arab Emirates': { code: '+971', flag: '🇦🇪' },
  'United Kingdom': { code: '+44', flag: '🇬🇧' },
  'United States': { code: '+1', flag: '🇺🇸' },
  'Uruguay': { code: '+598', flag: '🇺🇾' },
  'Uzbekistan': { code: '+998', flag: '🇺🇿' },
  'Vanuatu': { code: '+678', flag: '🇻🇺' },
  'Vatican City': { code: '+379', flag: '🇻🇦' },
  'Venezuela': { code: '+58', flag: '🇻🇪' },
  'Vietnam': { code: '+84', flag: '🇻🇳' },
  'Yemen': { code: '+967', flag: '🇾🇪' },
  'Zambia': { code: '+260', flag: '🇿🇲' },
  'Zimbabwe': { code: '+263', flag: '🇿🇼' },
};

// Sorted country names for dropdowns/datalists
export const SORTED_COUNTRY_NAMES = Object.keys(COUNTRY_PHONE_CODES).sort();

// Helper: get phone code for a country name (fallback to '+' if unknown)
export function getPhoneCode(country: string): string {
  return COUNTRY_PHONE_CODES[country]?.code || '+';
}

// Helper: get flag for a country name
export function getCountryFlag(country: string): string {
  return COUNTRY_PHONE_CODES[country]?.flag || '🌍';
}
